AI_CHAT_MODEL_PROVIDER_OPENAI = "OPENAI"
AI_EMBEDDING_MODEL_PROVIDER_OPENAI = "OPENAI"
GOOGLE_SEARCH_PROVIDER_GOOGLESEARCHPKG = "GOOGLESEARCHPKG"
WEBSCRAPER_TYPE_DEFAULT = "DEFAULT"
INDEXDB_TYPE_HNSW = "HNSW"

AI_CHAT_ARRAY_RESPONSE_SEPERATOR = ";"
NO_QUESTION_ASKED = "no question asked"
NO_QUESTION_ASKED_QUOAT = '"no question asked"'
